### PR TITLE
allow playing youtube videos from the url

### PR DESCRIPTION
**Pull request by vavrecan**

### CODE REVIEW

**Comment by brainfoolong** [comment]
Hi. Thanks for the pull request. But have you tested all this when this youtube-dl is not installed?

**Comment by vavrecan** [comment]
Yes this should be setting in the ui. Otherwise nothing happens. Can you add setting to detect youtube links?
Thanks

**Comment by brainfoolong** [comment]
Maybe i will do. But i don't like the `youtube-dl` dependency. Maybe i find something else. I reject this pull request for now.

Please do not submit incomplete and not well working pull requests. 

Thank you.

**Comment by vavrecan** [comment]
there is no easy way without youtube-dl.
Cheers.

**Comment by vavrecan** [comment]
you could try this https://github.com/Athlon1600/youtube-downloader

**Pull request closed without merging**
